apiVersion: v1
kind: Pod
metadata:
  name: minimum-required-mount
  labels:
    app: minimum-required-mount
spec:
  containers:
  - name: minimum-required-mount
    image: httpd:2.4.57
    securityContext:
      readOnlyRootFilesystem: true
    volumeMounts:
    - name: logs
      mountPath: /usr/local/apache2/logs
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  volumes:
  - name: logs
    emptyDir: {}
