apiVersion: v1
kind: Pod
metadata:
  name: mutable
  labels:
    app: mutable
spec:
  containers:
  - name: mutable
    image: ubuntu:20.04
    command: ["/bin/bash", "-c", "while true; do sleep 1; done"]
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"