apiVersion: v1
kind: Pod
metadata:
  name: privilege-escalation-false
  labels:
    app: privilege-escalation-false
spec:
  containers:
  - name: privilege-escalation-false
    image: privilege-escalation-container-image
    command: ["/bin/sh", "-c", "while :; do sleep 10; done"]
    imagePullPolicy: Never
    securityContext:
      allowPrivilegeEscalation: false
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"