apiVersion: v1
kind: Pod
metadata:
  name: leak
  labels:
    app: leak
spec:
  containers:
  - name: leak
    image: leak-container-image:latest
    imagePullPolicy: Never
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"