apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: vulnerable-pod-network-policy
  namespace: network-policy-ns
spec:
  podSelector:
    matchLabels:
      app: vulnerable-pod
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - ports:
    - protocol: TCP
      port: 80
