apiVersion: v1
kind: Pod
metadata:
  name: bar-web
  labels:
    app: bar-web
spec:
  containers:
  - name: bar-web
    image: limited-resources-container-image
    imagePullPolicy: Never
    env:
    - name: APP_NAME
      value: "bar-web"
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"