apiVersion: v1
kind: Service
metadata:
  name: bar-web
  labels:
    app: bar-web
spec:
  selector:
    app: bar-web
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8002
    targetPort: 8080
