apiVersion: v1
kind: Pod
metadata:
  name: taint-node
  labels:
    app: taint-node
spec:
  containers:
  - name: taint-node
    image: ubuntu:22.04
    resources:
      requests:
        cpu: "250m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
  tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
  nodeSelector:
    node-restriction.kubernetes.io/dedicated: "true"
