apiVersion: v1
kind: Pod
metadata:
  name: unauthorized-user
  labels:
    app: unauthorized-user
spec:
  containers:
    - name: unauthorized-user
      image: designate-user-container-image
      command: ["/bin/sh", "-c", "while :; do echo 'by unauthorized user' >> author.txt; sleep 10; done"]
      imagePullPolicy: Never
      securityContext:
        runAsNonRoot: true
        runAsUser: 2000
        runAsGroup: 2000
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
