apiVersion: v1
kind: Pod
metadata:
  name: no-sa-token-pod
  labels:
    app: no-sa-token
spec:
  containers:
  - name: no-sa-token
    image: ubuntu:22.04
    command: ["/bin/sh", "-c", "while true; do sleep 10; done"]
    resources:
      requests:
        cpu: "250m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
  automountServiceAccountToken: false
