apiVersion: v1
kind: Pod
metadata:
  name: reliable
  labels:
    app: reliable
spec:
  containers:
  - name: reliable
    image: $IMAGE
    imagePullPolicy: Always
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  imagePullSecrets:
    - name: regcred